server:
  port: 8085
#  servlet:
#    context-path: /test
spring:
  application:
    name: storytelling-spi-cn
  config:
    import: nacos:mall-shardingsphere?group=DEFAULT_GROUP

  cloud:
    nacos:
      discovery:
        #服务注册地址
        server-addr:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/storytelling?allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:12345678}
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 0
      maximum-pool-size: 20
      idle-timeout: 10000
      auto-commit: true
      connection-test-query: SELECT 1
  cache:
    type: redis
    redis:
      cache-null-values: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      password: ${REDIS_PASSWORD:}
      lettuce:
        pool:
          #最大连接数
          max-active: 2000
          #最大阻塞等待时间(负数表示没限制)
          max-wait: -1ms
          #最大空闲
          max-idle: 10
          #最小空闲
          min-idle: 0
          #连接超时时间
      connect-timeout: 10s
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}
    # 消息确认配置
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    # 消费者配置
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        concurrency: 5
        max-concurrency: 10
        # 重试配置
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          multiplier: 1.0
          max-interval: 10000
#sa-token:
#  token-name: token
#  timeout: 36000
#  token-style: random-32
#  is-concurrent: false
#  auto-renew: true
#  activity-timeout: 1800
wxpay:
  # 商户号
  mch-id: ${WXPAY_MCH_ID:1234567890}
  # 商户API证书序列号
  mch-serial-no: ${WXPAY_MCH_SERIAL_NO:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX}
  # 商户私钥文件路径
  private-key-path: ${WXPAY_PRIVATE_KEY_PATH:classpath:cert/apiclient_key.pem}
  # APIv3密钥
  api-v3-key: ${WXPAY_API_V3_KEY:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX}
  # 应用ID
  appid: ${WXPAY_APPID:wxXXXXXXXXXXXXXXXX}
  # 微信支付API域名
  domain: ${WXPAY_DOMAIN:https://api.mch.weixin.qq.com}
  # 支付回调通知域名
  notify-domain: ${WXPAY_NOTIFY_DOMAIN:https://your-domain.com}
file:
  dataPath: C:\Users\chennian\Desktop\qrcode
  environment: dev
  domain: http:// #二维码数据存储路径
  path: \
logging:
  config: classpath:logback/logback-dev.xml
  level:
    com.baomidou.mybatisplus: debug
