server:
  port: 18085
#  servlet:
#    context-path: /admin
spring:
  application:
    name: storytelling-admin
  cloud:
    nacos:
      discovery:
        #服务注册地址
        server-addr: http://
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/storytelling?allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: ${spring.datasource.username:}
    password: ${spring.datasource.password:}
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 0
      maximum-pool-size: 20
      idle-timeout: 10000
      auto-commit: true
      connection-test-query: SELECT 1
  cache:
    type: redis
    redis:
      cache-null-values: true
  data:
    redis:
      host:
      port: 6379
      database: 0
      lettuce:
        pool:
          #最大连接数
          max-active: 2000
          #最大阻塞等待时间(负数表示没限制)
          max-wait: -1ms
          #最大空闲
          max-idle: 10
          #最小空闲
          min-idle: 0
          #连接超时时间
      connect-timeout: 10s
      password: ${spring.data.redis.password:}
    mongodb:
      uri: mongodb://${mongodb.username:}:${mongodb.password:}@127.0.0.1:27017/storytelling?authSource=storytelling&tls=false&retryWrites=true&maxPoolSize=100&minPoolSize=10&maxIdleTimeMS=120000
      auto-index-creation: true
  mail:
    host: smtp.163.com
    port: 465
    username: ${spring.mail.username:}
    password: ${spring.mail.password:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
flowable:
  database-schema-update: true
  async-executor-activate: false
file:
  dataPath: /appdata/qrcode/
  environment: prod
  domain: http://
  path: /
logging:
  config: classpath:logback/logback-prod.xml
  level:
    com.chennian.storytelling.admin.controller.workflow: DEBUG
    com.chennian.storytelling.admin.interceptor: INFO
    com.baomidou.mybatisplus: debug
