# 服务器配置
server:
  port: 8082

# Spring 配置
spring:
  application:
    name: storytelling-product
  profiles:
    active: dev
  
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/storytelling_product?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  
  # Redis 配置
  redis:
    host: localhost
    port: 6379
    password:
    database: 2
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  
  # Nacos 服务发现配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: dev
        group: DEFAULT_GROUP
      config:
        server-addr: localhost:8848
        namespace: dev
        group: DEFAULT_GROUP
        file-extension: yml
        shared-configs:
          - data-id: common.yml
            group: DEFAULT_GROUP
            refresh: true
  
  # 分布式链路追踪
  sleuth:
    sampler:
      probability: 1.0
    zipkin:
      base-url: http://localhost:9411
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

# MyBatis Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      update-strategy: NOT_NULL
      insert-strategy: NOT_NULL
      select-strategy: NOT_EMPTY
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.chennian.storytelling.product.entity

# 日志配置
logging:
  level:
    com.chennian.storytelling: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId},%X{spanId}] %logger{50} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId},%X{spanId}] %logger{50} - %msg%n'
  file:
    name: logs/storytelling-product.log
    max-size: 100MB
    max-history: 30

# 监控端点配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Feign 配置
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000
        logger-level: basic

# Sa-Token 配置
sa-token:
  token-name: Authorization
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: false
  is-print: false
  jwt-secret-key: abcdefghijklmnopqrstuvwxyz
  redis:
    database: 1

# Swagger 配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  info:
    title: 故事叙述商品服务 API
    description: 商品服务相关接口文档
    version: 1.0.0
    contact:
      name: chennian
      email: chennian@example.com
  group-configs:
    - group: 'product'
      display-name: '商品管理'
      paths-to-match: '/api/product/**'
    - group: 'category'
      display-name: '分类管理'
      paths-to-match: '/api/category/**'
    - group: 'brand'
      display-name: '品牌管理'
      paths-to-match: '/api/brand/**'

# 业务配置
business:
  # 商品配置
  product:
    # 默认图片
    default-image: https://example.com/default-product.jpg
    # 图片上传路径
    upload-path: /uploads/products/
    # 允许的图片格式
    allowed-image-types: jpg,jpeg,png,gif,webp
    # 图片大小限制（MB）
    max-image-size: 5
  
  # 分类配置
  category:
    # 最大层级
    max-level: 5
    # 默认图标
    default-icon: fa-folder
    # 默认图片
    default-image: https://example.com/default-category.jpg
  
  # 品牌配置
  brand:
    # 默认LOGO
    default-logo: https://example.com/default-brand.jpg
    # LOGO上传路径
    logo-upload-path: /uploads/brands/

# 对象存储配置（七牛云）
qiniu:
  access-key: your-access-key
  secret-key: your-secret-key
  bucket: storytelling-product
  domain: https://your-domain.com
  region: z0

# Elasticsearch 配置
elasticsearch:
  host: localhost
  port: 9200
  username:
  password:
  index:
    product: storytelling_product
    category: storytelling_category
    brand: storytelling_brand